package fr.pinguet62.jsfring.model;

// Generated 16 août 2014 18:49:09 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", catalog = "dictionary")
public class Profile implements java.io.Serializable {

    private Integer id;
    private Set<Right> rights = new HashSet<Right>(0);
    private String title;
    private Set<User> users = new HashSet<User>(0);

    public Profile() {
    }

    public Profile(int id, String title) {
        this.id = id;
        this.title = title;
    }

    public Profile(int id, String title, Set<User> users, Set<Right> rights) {
        this.id = id;
        this.title = title;
        this.users = users;
        this.rights = rights;
    }

    public Profile(String title) {
        this.title = title;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (!(obj instanceof Profile))
            return false;
        Profile other = (Profile) obj;
        return Objects.equals(id, other.id);
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return id;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "profiles_rights", catalog = "dictionary", joinColumns = { @JoinColumn(name = "PROFILE", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "RIGHT_CODE", nullable = false, updatable = false) })
    public Set<Right> getRights() {
        return rights;
    }

    @Column(name = "TITLE", nullable = false, length = 30)
    public String getTitle() {
        return title;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "users_profiles", catalog = "dictionary", joinColumns = { @JoinColumn(name = "PROFILE", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "USER", nullable = false, updatable = false) })
    public Set<User> getUsers() {
        return users;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setRights(Set<Right> rights) {
        this.rights = rights;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

}
