package fr.pinguet62.jsfring.model;

// Generated 16 août 2014 18:49:09 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "\"USER\"")
public class User implements java.io.Serializable {

    private Date lastConnection;
    private String login;
    private String password;
    private String email;
    private Set<Profile> profiles = new HashSet<Profile>(0);

    public User() {
    }

    public User(String login, String password, String email) {
        this.login = login;
        this.password = password;
        this.email = email;
    }

    public User(String login, String password, String email, Set<Profile> profiles) {
        this.login = login;
        this.password = password;
        this.email = email;
        this.profiles = profiles;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "last_connection", nullable = false)
    public Date getLastConnection() {
        return lastConnection;
    }

    @Id
    @Column(name = "LOGIN", unique = true, nullable = false, length = 30)
    public String getLogin() {
        return login;
    }

    @Column(name = "PASSWORD", nullable = false, length = 30)
    public String getPassword() {
        return password;
    }

    @Column(name = "EMAIL", nullable = false)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "users_profiles", joinColumns = { @JoinColumn(name = "\"USER\"", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "profile", nullable = false, updatable = false) })
    public Set<Profile> getProfiles() {
        return profiles;
    }

    public void setLastConnection(Date lastConnection) {
        this.lastConnection = lastConnection;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setProfiles(Set<Profile> profiles) {
        this.profiles = profiles;
    }

}
