package fr.pinguet62.dictionary.model;

// Generated 16 août 2014 18:49:09 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Description generated by hbm2java
 */
@Entity
@Table(name = "description", catalog = "dictionary")
public class Description implements java.io.Serializable {

    private String content;
    private Integer id;
    private Keyword keyword;
    private Language language;
    private String title;

    public Description() {
    }

    public Description(int id, Language language, Keyword keyword,
            String title, String content) {
        this.id = id;
        this.language = language;
        this.keyword = keyword;
        this.title = title;
        this.content = content;
    }

    public Description(Language language, Keyword keyword, String title,
            String content) {
        this.language = language;
        this.keyword = keyword;
        this.title = title;
        this.content = content;
    }

    public Description(Language language, String title, String content) {
        this.language = language;
        this.title = title;
        this.content = content;
    }

    @Column(name = "CONTENT", nullable = false, length = 999)
    public String getContent() {
        return content;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "KEYWORD")
    public Keyword getKeyword() {
        return keyword;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LANGUAGE", nullable = false)
    public Language getLanguage() {
        return language;
    }

    @Column(name = "TITLE", nullable = false, length = 50)
    public String getTitle() {
        return title;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setKeyword(Keyword keyword) {
        this.keyword = keyword;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
