package fr.pinguet62.dictionary.model;

// Generated 16 août 2014 18:49:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Right generated by hbm2java
 */
@Entity
@Table(name = "right", catalog = "dictionary")
public class Right implements java.io.Serializable {

    private String code;
    private String title;
    private Set<Profile> profiles = new HashSet<Profile>(0);

    public Right() {
    }

    public Right(String code, String title) {
        this.code = code;
        this.title = title;
    }

    public Right(String code, String title, Set<Profile> profiles) {
        this.code = code;
        this.title = title;
        this.profiles = profiles;
    }

    @Id
    @Column(name = "CODE", unique = true, nullable = false, length = 30)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "TITLE", nullable = false, length = 50)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "profiles_rights", catalog = "dictionary", joinColumns = { @JoinColumn(name = "RIGHT", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "PROFILE", nullable = false, updatable = false) })
    public Set<Profile> getProfiles() {
        return this.profiles;
    }

    public void setProfiles(Set<Profile> profiles) {
        this.profiles = profiles;
    }

}
